"""Private staging storage for uploaded knowledge documents."""

from __future__ import annotations

from pathlib import Path, PurePosixPath
from typing import Any, Protocol, cast


class DocumentStorageError(RuntimeError):
    """The staging storage cannot safely read or write a document."""


class DocumentStorage(Protocol):
    """Storage contract shared by local development and object storage adapters."""

    def store(self, job_id: str, file_name: str, content: bytes, *, content_type: str) -> str:
        """Persist immutable bytes and return an opaque storage key."""

    def read(self, key: str) -> bytes:
        """Read an object by an opaque key."""


class LocalDocumentStorage:
    """Local implementation of the storage boundary used by the first deployment.

    The job stores an opaque key rather than a user-provided path. Production can replace
    this class with an S3/OSS adapter without changing review, retry, or indexing logic.
    """

    def __init__(self, root_dir: str) -> None:
        self._root = Path(root_dir).expanduser().resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def store(self, job_id: str, file_name: str, content: bytes, *, content_type: str = "") -> str:
        """Write one immutable staged object and return its opaque relative key."""

        suffix = PurePosixPath(file_name).suffix.lower()
        if not suffix or len(suffix) > 10 or not suffix[1:].isalnum():
            raise DocumentStorageError("uploaded file must have a safe extension")
        key = f"{job_id}{suffix}"
        target = self._safe_path(key)
        temporary = target.with_suffix(target.suffix + ".tmp")
        try:
            temporary.write_bytes(content)
            temporary.replace(target)
        except OSError as exc:
            raise DocumentStorageError("could not persist uploaded document") from exc
        return key

    def read(self, key: str) -> bytes:
        """Read an object only after resolving it below the configured staging root."""

        try:
            return self._safe_path(key).read_bytes()
        except OSError as exc:
            raise DocumentStorageError("could not read staged document") from exc

    def _safe_path(self, key: str) -> Path:
        """Reject traversal and absolute paths before touching the filesystem."""

        candidate = (self._root / key).resolve()
        if candidate.parent != self._root or Path(key).is_absolute():
            raise DocumentStorageError("invalid storage key")
        return candidate


class S3DocumentStorage:
    """S3-compatible object storage adapter, including MinIO and OSS gateways.

    boto3 is synchronous, so network calls are moved to worker threads. The rest of the
    Agent service only sees the small storage contract and does not depend on a vendor SDK.
    """

    def __init__(
        self,
        *,
        endpoint_url: str,
        region: str,
        bucket: str,
        access_key: str,
        secret_key: str,
    ) -> None:
        if not endpoint_url or not bucket or not access_key or not secret_key:
            raise ValueError("S3 storage requires endpoint, bucket, access key, and secret key")
        import boto3  # type: ignore[import-untyped]

        self._bucket = bucket
        self._client: Any = boto3.client(
            "s3",
            endpoint_url=endpoint_url,
            region_name=region,
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
        )

    def store(self, job_id: str, file_name: str, content: bytes, *, content_type: str = "") -> str:
        suffix = PurePosixPath(file_name).suffix.lower()
        if not suffix or len(suffix) > 10 or not suffix[1:].isalnum():
            raise DocumentStorageError("uploaded file must have a safe extension")
        key = f"knowledge/{job_id}{suffix}"
        try:
            self._client.put_object(
                Bucket=self._bucket,
                Key=key,
                Body=content,
                ContentType=content_type or "application/octet-stream",
            )
        except Exception as exc:
            raise DocumentStorageError("could not persist uploaded document") from exc
        return key

    def read(self, key: str) -> bytes:
        if not _is_safe_s3_key(key):
            raise DocumentStorageError("invalid storage key")
        try:
            response = self._client.get_object(Bucket=self._bucket, Key=key)
            return cast(bytes, response["Body"].read())
        except Exception as exc:
            raise DocumentStorageError("could not read staged document") from exc


def _is_safe_s3_key(key: str) -> bool:
    """Allow only keys generated by this service, never arbitrary object paths."""

    parts = PurePosixPath(key).parts
    return bool(parts) and parts[0] == "knowledge" and ".." not in parts and len(parts) == 2
